# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kJI3DT11BAAYHKXHMmmHySeZpGNVvRD
"""

streamlit
supabase
pandas
requests
python-dotenv
geopy
matplotlib
scikit-learn
email-validator